### ISSUE TITLE
post.firstImage does not work

### ISSUE THREAD

**Issue by rteinze** [zeroseven/z7_blog#1]
In the Fluid template and partial (list item) all works fine but the ``post.firstImage`` does not. There is an image at the target page/post but the object firstImage (``<f:debug>{_all}</f:debug>``) keeps NULL.

**Comment by srosskopf** [comment]
Hey there! Thank you for using our blog extension. 

The `post.firstImage` should be an image from the blog posts page properties. As you can see in the [abstract page model](https://github.com/zeroseven/z7_blog/blob/master/Classes/Domain/Model/AbstractPageModel.php#L186) here, the blog gets the first media asset and also checks if it is a valid image file type.

There are a lot of configuration variables here, so this is my first guess. Just wanted to clarify that these images come from the page properties of a blog post page and not any content like textmedia or something.

**Comment by srosskopf** [comment]
Another thing: have you tried just using the `post.firstImage` in a <f:image> or something? Sometimes the debug says it's null but it is actually there, just not in time when the debug is compiled.

**Comment by srosskopf** [comment]
I'll go ahead and close this issues for lack of feedback.
