### ISSUE TITLE
Idea: Structured data into a Fluid Partial

### ISSUE THREAD

**Issue by alsodenn** [zeroseven/z7_blog#3]
How about inserting the structured data into a Fluid Partial? Then you could easily adapt them. At the moment, for example, the author's social profiles are missing. Everyone has their own preferences about what should and should not be included ;-). A partial would be an easy way to adapt this yourself.

**Comment by raphaelthanner** [comment]
Hello @alsodenn, you are definitely right.. We will add the authors social profiles to the structured data soon. Currently we added different ways to extend or manipulate the structure data:

1. Add [static typoscript](https://github.com/zeroseven/z7_blog/blob/master/README.md#structured-data)
2. Add methode `getStructuredData` to your Post model.  (see [Extend models and demands classes
](https://github.com/zeroseven/z7_blog/blob/master/README.md#extend-models-and-demands-classes))
3. Use the [StructuredDataEvent](https://github.com/zeroseven/z7_blog/blob/master/Classes/Event/StructuredDataEvent.php) (PSR-14 Events) to manipulate the structured data

In practice, the arrays that are automatically converted into structured data have proven themselves quite well, as the data only has to be provided. On the other hand, the syntax in the Fluid template with curly brackets often leads to problems.

For the time being, we consider this to be enough ways to manipulate the structured data that is put out. Thank you for your input and let us know if you have any additional feedback.
