### ISSUE TITLE
documentation for editors

### ISSUE THREAD

**Issue by rteinze** [zeroseven/z7_blog#4]
I don't get the Authors dropdown (post_author) in a blog post filled up with names. Some authors are stored in a sys folder but where I have to point the sys folder as blog authors folder?

And in general - where do I find any documentation for editors?

**Comment by raphaelthanner** [comment]
Hi, did you already assign the pid of the directory where your author information is stored to this constant: `plugin.tx_z7blog.persistence.storagePid`.

Thank you for your hint on the documentation. We will continue to improve the docs and try to appeal to editors as well as developers.

**Comment by rteinze** [comment]
Yes I did.

**Comment by raphaelthanner** [comment]
Ok good. Did you also include the typoscript configuration in your root template?

**Comment by raphaelthanner** [comment]
I'll go ahead and close this issues for lack of feedback.
