### ISSUE TITLE
Compatibility with TYPO3 12

### ISSUE THREAD

**Issue by timdreier** [zeroseven/z7_blog#8]
Are there plans for a version for TYPO3 12? :). Thank you for your feedback!

**Comment by raphaelthanner** [comment]
Hi @timdreier, we are working on it right now.  There is already a [branch](https://github.com/zeroseven/z7_blog/tree/TYPO3-v12) available.

I think that we can publish a release soon.

**Comment by timdreier** [comment]
Hi @raphaelthanner,
thank you, haven't seen the v12 branch when I wrote the issue. Found it yesterday - works great so far. Only issue I found so far is a missing `return $this->htmlResponse();` in the AuthorController :)
